# -*- coding: utf-8 -*-
"""Exercise Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aiCupI6b1_UU2YWae7VyI18ppfgMDPP0
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

import io
scores = pd.read_csv(io.BytesIO(uploaded['exam_scores.csv']))

scores

scores.info()

scores.head() # to see first five of dataframe

scores.head(3)

scores.tail() # to see last five of dataframe

from google.colab import files
uploaded = files.upload()

import io
rs_tangerang = pd.read_csv(io.BytesIO(uploaded['31_RS_Tangerang.csv']))

rs_tangerang